packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.56.1
  "@playwright/test": 1.56.1
  "@vue/compiler-core": 3.5.22
  "@vue/compiler-dom": 3.5.22
  "@vue/compiler-sfc": 3.5.22
  "@vue/compiler-ssr": 3.5.22
  "@vue/shared": 3.5.22
  chart.js: 4.5.1
  nuxt: 4.2.0
  playwright: 1.56.1
  playwright-core: 1.56.1
  sass-embedded: 1.93.2
  typescript: 5.9.3
  vite: 7.1.12
  vue: 3.5.22

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
