packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.52.0
  "@playwright/test": 1.52.0
  "@vue/compiler-core": 3.5.16
  "@vue/compiler-dom": 3.5.16
  "@vue/compiler-sfc": 3.5.16
  "@vue/compiler-ssr": 3.5.16
  "@vue/shared": 3.5.16
  chart.js: 4.4.9
  "playwright": 1.52.0
  "playwright-core": 1.52.0
  vue: 3.5.16
  sass-embedded: 1.89.1
  typescript: 5.8.3
  vite: 6.3.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
