packages:
  - apps/*
  - packages/*

allowBuilds:
  "@parcel/watcher": true
  better-sqlite3: true
  esbuild: true
  sharp: true
  simple-git-hooks: true

blockExoticSubdeps: true

catalog:
  "@playwright/experimental-ct-vue": 1.58.1
  "@playwright/test": 1.58.1
  "@vue/compiler-core": 3.5.27
  "@vue/compiler-dom": 3.5.27
  "@vue/compiler-sfc": 3.5.27
  "@vue/compiler-ssr": 3.5.27
  "@vue/shared": 3.5.27
  chart.js: 4.5.1
  nuxt: 4.2.2
  playwright: 1.58.1
  playwright-core: 1.58.1
  sass-embedded: 1.97.3
  typescript: 5.9.3
  vite: 7.3.1
  vue: 3.5.27

minimumReleaseAge: 2880

trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
