packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.57.0
  "@playwright/test": 1.57.0
  "@vue/compiler-core": 3.5.27
  "@vue/compiler-dom": 3.5.27
  "@vue/compiler-sfc": 3.5.27
  "@vue/compiler-ssr": 3.5.27
  "@vue/shared": 3.5.27
  chart.js: 4.5.1
  nuxt: 4.3.1
  playwright: 1.57.0
  playwright-core: 1.57.0
  sass-embedded: 1.97.3
  typescript: 5.9.3
  vite: 7.3.1
  vue: 3.5.27

# Security settings (See: https://pnpm.io/supply-chain-security)
trustPolicy: "no-downgrade"
trustPolicyExclude:
  - "chokidar@4.0.3" # See https://github.com/paulmillr/chokidar/issues/1440
  - "semver@6.3.1" # See https://github.com/npm/node-semver/issues/838
minimumReleaseAge: 2880 # Wait two days after a new version release - This is in sync with the `dependabot.yml` `cooldown` config
blockExoticSubdeps: true
allowBuilds:
  "@parcel/watcher": true # Downloads binary
  "better-sqlite3": true # Downloads binary
  "esbuild": true # Downloads binary
  "sharp": true # Downloads binary
  "simple-git-hooks": true # Setup and update git hooks
