packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.55.0
  "@playwright/test": 1.55.0
  "@vue/compiler-core": 3.5.21
  "@vue/compiler-dom": 3.5.21
  "@vue/compiler-sfc": 3.5.21
  "@vue/compiler-ssr": 3.5.21
  "@vue/shared": 3.5.21
  chart.js: 4.5.0
  nuxt: 4.1.2
  playwright: 1.55.0
  playwright-core: 1.55.0
  sass-embedded: 1.93.1
  typescript: 5.9.2
  vite: 7.1.7
  vue: 3.5.21

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
