packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.57.0
  "@playwright/test": 1.57.0
  "@vue/compiler-core": 3.5.26
  "@vue/compiler-dom": 3.5.26
  "@vue/compiler-sfc": 3.5.26
  "@vue/compiler-ssr": 3.5.26
  "@vue/shared": 3.5.26
  chart.js: 4.5.1
  nuxt: 4.2.2
  playwright: 1.57.0
  playwright-core: 1.57.0
  sass-embedded: 1.97.2
  typescript: 5.9.3
  vite: 7.3.1
  vue: 3.5.26

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
