packages:
  - apps/*
  - packages/*

catalog:
  "@vue/compiler-core": 3.5.14
  "@vue/compiler-dom": 3.5.14
  "@vue/compiler-sfc": 3.5.14
  "@vue/compiler-ssr": 3.5.14
  "@vue/shared": 3.5.14
  chart.js: 4.4.9
  vue: 3.5.14
  sass-embedded: 1.89.0
  typescript: 5.8.3
  vite: 6.3.5

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
