packages:
  - "apps/*"
  - "packages/*"

catalog:
  "@vue/compiler-core": "3.5.13"
  "@vue/compiler-dom": "3.5.13"
  "@vue/compiler-sfc": "3.5.13"
  "@vue/compiler-ssr": "3.5.13"
  "@vue/shared": "3.5.13"
  "chart.js": "^4.4.7"
  "vue": "3.5.13"
  "sass-embedded": "1.85.0"
  "typescript": "5.7.3"
  "vite": "6.1.0"
