packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.54.2
  "@playwright/test": 1.54.2
  "@vue/compiler-core": 3.5.18
  "@vue/compiler-dom": 3.5.18
  "@vue/compiler-sfc": 3.5.18
  "@vue/compiler-ssr": 3.5.18
  "@vue/shared": 3.5.18
  chart.js: 4.5.0
  playwright: 1.54.2
  playwright-core: 1.54.2
  sass-embedded: 1.90.0
  typescript: 5.9.2
  vite: 7.1.1
  vue: 3.5.18

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
