packages:
  - apps/*
  - packages/*

catalog:
  "@playwright/experimental-ct-vue": 1.57.0
  "@playwright/test": 1.57.0
  "@vue/compiler-core": 3.5.25
  "@vue/compiler-dom": 3.5.25
  "@vue/compiler-sfc": 3.5.25
  "@vue/compiler-ssr": 3.5.25
  "@vue/shared": 3.5.25
  chart.js: 4.5.1
  nuxt: 4.2.1
  playwright: 1.57.0
  playwright-core: 1.57.0
  sass-embedded: 1.93.3
  typescript: 5.9.3
  vite: 7.2.4
  vue: 3.5.25

onlyBuiltDependencies:
  - "@parcel/watcher"
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
