name: Setup node
description: Custom node setup for onyx

inputs:
  pnpm_install_command:
    default: "pnpm install --frozen-lockfile"
    description: Command to run to install dependencies

runs:
  using: "composite"
  steps:
    - name: 🧑‍💼 Setup pnpm
      uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

    - name: 🏗️ Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version-file: .node-version
        cache: pnpm

    # *pnpm* uses *npm* under the hood for publishing.
    # For publishing securely the latest npm version should always be used.
    - name: Keep npm up-to-date
      run: npm install -g npm@latest
      shell: bash

    - name: 📆 Get Date
      id: get-date
      run: |
        echo "day=$(/bin/date -u "+%d")" >> $GITHUB_OUTPUT
        echo "month=$(/bin/date -u "+%m")" >> $GITHUB_OUTPUT
        echo "year=$(/bin/date -u "+%Y")" >> $GITHUB_OUTPUT
      shell: bash

    - name: 🫙 Cache
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          **/.cache
        key: build-caches-${{ steps.get-date.outputs.year }}-${{ steps.get-date.outputs.month }}-${{ steps.get-date.outputs.day }}
        restore-keys: |
          build-caches-${{ steps.get-date.outputs.year }}-${{ steps.get-date.outputs.month }}-${{ steps.get-date.outputs.day }}
          build-caches-${{ steps.get-date.outputs.year }}-${{ steps.get-date.outputs.month }}-
          build-caches-${{ steps.get-date.outputs.year }}-
          build-caches-

    - name: 📦 Install dependencies
      run: ${{ inputs.pnpm_install_command }}
      shell: bash
