name: Setup node
description: Custom node setup for onyx

inputs:
  NODE_AUTH_TOKEN:
    default: ""
    description: If the npm registry setup should be authenticated.

runs:
  using: "composite"
  steps:
    - name: 🧑‍💼 Setup pnpm
      uses: pnpm/action-setup@v4

    - name: 🔐 Setup Node.js
      if: ${{ inputs.NODE_AUTH_TOKEN != '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: "https://registry.npmjs.org/"
        scope: sit-onyx
      env:
        NODE_AUTH_TOKEN: ${{ inputs.NODE_AUTH_TOKEN }}

    - name: 🏗️ Setup Node.js
      if: ${{ inputs.NODE_AUTH_TOKEN == '' }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: 📆 Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: 🫙 Cache
      uses: actions/cache@v4
      with:
        path: |
          **/.cache
        key: build-caches-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('**/.cache') }}
        restore-keys: |
          build-caches-${{ runner.os }}-${{ steps.get-date.outputs.date }}-
          build-caches-${{ runner.os }}-

    - name: 📦 Install dependencies
      run: pnpm install
      shell: bash
