name: Setup node
description: Custom node setup for onyx

inputs:
  authenticated:
    default: false
    description: If the npm registry setup should be authenticated.

runs:
  using: "composite"
  steps:
    - name: 🧑‍💼 Setup pnpm
      uses: pnpm/action-setup@v4

    - name: 🔐 Setup Node.js
      if: ${{ inputs.authenticated == true }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm
        registry-url: "https://registry.npmjs.org/"
        scope: sit-onyx
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: 🏗️ Setup Node.js
      if: ${{ inputs.authenticated == false }}
      uses: actions/setup-node@v4
      with:
        node-version-file: .node-version
        cache: pnpm

    - name: 🫙 Cache
      uses: actions/cache@v4
      with:
        path: |
          **/.turbo
          **/.cache
        key: ${{ runner.os }}-caches

    - name: 📦 Install dependencies
      run: pnpm install
