name: 🚨 Run component tests
description: Runs Playwright component tests (node and pnpm must be setup before)

inputs:
  clean-snapshots:
    required: false
    description: Whether to remove all snapshots before running
  update-snapshots:
    required: false
    description: Whether to update the Playwright snapshots

runs:
  using: "composite"
  steps:
    # install system dependencies for Playwright
    # see: https://playwright.dev/python/docs/browsers#install-system-dependencies
    - name: 📦 Install Playwright system dependencies
      shell: bash
      run: pnpm exec playwright install-deps

    - name: 🗑️ Delete existing screenshots
      if: ${{ inputs.clean-snapshots == 'true' }}
      shell: bash
      run: |
        rm -rf  ./packages/chartjs-plugin/playwright/snapshots
        rm -rf ./packages/headless/playwright/snapshots
        rm -rf ./packages/sit-onyx/playwright/snapshots

    - name: 🚨 Run component tests
      shell: bash
      run: pnpm run test:components:all ${{ inputs.update-snapshots == 'true' && '--update-snapshots' || '' }}

    - name: Upload test results artifact
      uses: actions/upload-artifact@v4
      if: always() # needed to also upload test results when they failed (useful for debugging)
      with:
        name: test-results
        path: |
          packages/chartjs-plugin/playwright-report
          packages/chartjs-plugin/test-results
          packages/headless/playwright-report
          packages/headless/test-results
          packages/sit-onyx/playwright-report
          packages/sit-onyx/test-results
