name: Request a new feature 🚀
description: >-
  Do you want to request a new feature to be added to onyx? You can request it
  with the form below.
title: "[Feature request]: "
labels:
  - enhancement

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        Please describe the use case as detailed as possible. **Note**: Describe
        the underlying problem / use case, no technical details.
      placeholder: "Example: I want to be able to filter the table by ..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: >-
        Do you already have an idea how this feature could be implemented
        technically? If not, don't worry, we will take a look at it.
      placeholder: >-
        Example: Add a property "filters" to the table component which does ...

  - type: checkboxes
    id: confirm
    attributes:
      label: Confirmations
      options:
        - label: >-
            I have checked that there is not already a feature request for this
            feature.
          required: true
        - label: >-
            I confirm that are no sensitive information included in this feature
            request. e.g. credentials, internal project details (for employees of the Schwarz Group) etc.
          required: true
