name: Create a development story 📗
description: Story template for development tasks. Exclusively used by the onyx core team for project management.
title: "Implement|Define|Fix: ..."
projects:
  - SchwarzIT/5
labels:
  - dev

body:
  - type: textarea
    id: description
    attributes:
      label: Why?
      description: Add a short description and motivation for the story.
    validations:
      required: true

  - type: textarea
    id: content
    attributes:
      label: Content
      description: Add, adapt and remove the following sections as necessary
      value: >-
        ### Open Questions/To-dos

        <!-- Remove before ready -->

        <!-- [ ] Add question if any, use `@` to tag people -->

        ### Depends on

        <!-- Add links to tickets -->

        ### Design

        <!-- Add Figma link and comments here -->

        ### Acceptance criteria

        <!--  Add ticket specific AC, e.g., the expected behavior of a component -->

        ### Implementation details

        <!--
        add details if necessary, e.g.,
        - API proposal
        - relevant web APIs
        - learnings from other implementations
        - code snippets
        -->

        #### Reference implementations

        <!--  add links to other frameworks and WaWi, examples:
          - https://nuxt.com/docs/getting-started/installation
          - https://element-plus.org/en-US/component/overview.html
          - https://www.shadcn-vue.com/docs/components/accordion.html
          - https://design-system.w3.org/components for structural inspiration
        -->

        #### Applicable ARIA Pattern

        <!-- add link if applicable, see https://www.w3.org/WAI/ARIA/apg/patterns -->

        ### Definition of Done

        - The following component requirements are implemented:
          - [ ] skeleton
          - [ ] density
          - [ ] example usage added to `apps/demo-app/src/views/HomeView.vue`
        - covered by tests
          - [ ] functional tests (Playwright or unit test)
          - [ ] visual tests (Playwright screenshots)
        - [ ] follow-up tickets were created if necessary
        - [ ] updated version + documentation is deployed
        - [ ] Storybook can show the feature
        - [ ] Storybook code snippet of new/changed examples are checked that they are generated correctly
        - [ ] Namings are aligned with Figma

        **Approval**

        - Storybook <!-- add link to deployed storybook -->
        - Deployed Docs <!-- add link to deployed docs -->
        - [ ] approved by designer <!-- add your @username -->
        - [ ] approved by dev <!-- add your @username -->
    validations:
      required: true
