name: "[Team] Create a UX task 🎨"
description: Template for design tasks. Exclusively used by the onyx core team for project management.
title: "Concept|Adjust|Research"
type: Task
projects:
  - SchwarzIT/5
labels:
  - ux

body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Briefly describe what the UX task is about.

  - type: textarea
    id: dev-handover
    attributes:
      label: DEV handover checklist
      description: This checklist must be completed when the UX task is done and its handed over to the developer. You can shorten / extend the checklist as needed.
      value: |
        DEV handover done with: @ADD_DEV_NAME_HERE

        **Component**
        - [ ] defined main component name
        - [ ] defined which support components are used and how they are named
        - [ ] component has been hidden from publishing (until its implemented)
        - the following is explained to the DEV and documented:
            - [ ] all properties
            - [ ] truncation
            - [ ] responsiveness / wrapping behavior
            - [ ] min / max width

        **Documentation**
        - [ ] category for Figma and Storybook is defined
        - [ ] examples that should be shown in Storybook are defined and documented in Figma (documentation file)
        - [ ] component status "planned" has been added to the [docs overview](https://onyx.schwarz/#components)

        **Other**
        - [ ] DEV has either refined an implementation ticket or at least created a blank issue with a title
        - [ ] follow-up UX tickets were created if necessary (add links below)
    validations:
      required: true
