blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/schwarzit/onyx/discussions/categories/q-a
    about: You have a question that might already be answered by the community? Take a look at the GitHub discussions!
