import "@/styles/index.scss";

export * from "@/components/OnyxAppLayout/types";
export { default as OnyxAppLayout } from "@/components/OnyxAppLayout/OnyxAppLayout.vue";
export * from "@/components/OnyxButton/types";
export { default as OnyxButton } from "@/components/OnyxButton/OnyxButton.vue";
export * from "@/components/OnyxCheckbox/types";
export * from "@/components/OnyxCheckboxGroup/types";
export { default as OnyxCheckboxGroup } from "@/components/OnyxCheckboxGroup/OnyxCheckboxGroup.vue";
export * from "@/components/OnyxHeadline/types";
export { default as OnyxHeadline } from "@/components/OnyxHeadline/OnyxHeadline.vue";
export * from "@/components/OnyxIcon/types";
export { default as OnyxIcon } from "@/components/OnyxIcon/OnyxIcon.vue";
export * from "@/components/OnyxLink/types";
export { default as OnyxLink } from "@/components/OnyxLink/OnyxLink.vue";
export * from "@/components/OnyxLoadingIndicator/types";
export { default as OnyxLoadingIndicator } from "@/components/OnyxLoadingIndicator/OnyxLoadingIndicator.vue";
export * from "@/components/OnyxPageLayout/types";
export { default as OnyxPageLayout } from "@/components/OnyxPageLayout/OnyxPageLayout.vue";
export * from "@/components/OnyxRadioButton/types";
export { default as OnyxRadioButtonGroup } from "@/components/OnyxRadioButtonGroup/OnyxRadioButtonGroup.vue";
export { default as OnyxSkeleton } from "@/components/OnyxSkeleton/OnyxSkeleton.vue";
export { default as TestInput } from "@/components/TestInput/TestInput.vue";
export * from "@/components/OnyxSwitch/types";
export { default as OnyxSwitch } from "@/components/OnyxSwitch/OnyxSwitch.vue";
export type { OnyxTranslations, ProvideI18nOptions } from "@/i18n";
export * from "@/types/colors";
export * from "@/types/fonts";
export * from "@/types/i18n";
export * from "@/types/utils";

export { createOnyx } from "@/utils/plugin";
