name: Cloud Foundry Push
description: Pushes / Deploys an application to Cloud Foundry using CLI version 8

inputs:
  endpoint:
    required: true
    description: API endpoint of Cloud Foundry
  org:
    required: true
    description: Name of the Cloud Foundry organization
  username:
    required: true
    description: Username of the Cloud Foundry service account
  password:
    required: true
    description: Password of the Cloud Foundry service account
  space:
    required: true
    description: Space to push to (e.g. dev, prod etc.). A corresponding manifest with name "manifest-<space>.yml" is expected
  working-directory:
    required: true
    description: Directory where the push command is executed in (manifest, Staticfile etc. must be placed inside this folder)
  varArgs:
    default: ""
    description: Variables argument strings used for variable substitution file in manifest. Must be provided in the form of `--var KEY1=VALUE1 --var KEY2=VALUE2`

runs:
  using: "composite"
  steps:
    # according to: https://docs.cloudfoundry.org/cf-cli/install-go-cli.html#pkg-linux
    - name: Install Cloud Foundry CLI 8
      shell: bash
      run: |
        wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
        echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
        sudo apt-get update
        sudo apt-get install cf8-cli

    - name: Login to Cloud Foundry
      shell: bash
      run: cf login -u "${{ inputs.username }}" -p "${{ inputs.password }}" -a "${{ inputs.endpoint }}" -o "${{ inputs.org }}" -s "${{ inputs.space }}"

    - name: Deploy (${{ inputs.space }})
      shell: bash
      run: cf push --manifest "./manifest-${{ inputs.space }}.yml" --strategy rolling ${{ inputs.varArgs }}
      working-directory: ${{ inputs.working-directory }}

    - name: Logout from Cloud Foundry
      shell: bash
      run: cf logout
