import { figma, html } from "@figma/code-connect/html";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */
figma.connect("<BASE_URL>?node-id=635-29719", {
  props: {
    label: figma.string("label"),
    color: figma.string("color"),
    mode: figma.string("mode"),
    state: figma.string("state"),
  },
  example: (props) =>
    html`<OnyxButton label=${props.label} color=${props.color} mode=${props.mode} />`,
  imports: ['import { OnyxButton } from "sit-onyx";'],
});
