name: Check code quality
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
  # see: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#configuring-continuous-integration-ci-workflows-for-merge-queues
  merge_group:

env:
  TURBO_TOKEN: ${{ secrets.TURBO_REMOTE_CACHE__TURBO_TOKEN }}

permissions:
  contents: read
  checks: read

jobs:
  # We run the build first standalone to ensure everything is cached for all other jobs
  build:
    name: Build and Cache
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "🛃 Harden the runner (Audit all outbound calls)"
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit

      - name: "🛒 Checkout Repository"
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/templates/node-setup

      # install system dependencies for Playwright
      # https://github.com/actions/runner-images/issues/7048
      - name: 📦 Install Playwright system dependencies
        id: first-playwright-install
        run: |
          set -ex
          pnpm exec playwright install --only-shell --with-deps firefox webkit chromium-headless-shell

      - name: 🔎 Run Playwright tests
        run: pnpm test:playwright src/components/OnyxImage --project webkit --repeat-each 100 -x
        working-directory: packages/sit-onyx
        env:
          PW_UPDATE_SNAPSHOTS: "true"
