name: Compliance

on:
  pull_request:
  push: { branches: [main] }
  schedule:
    - cron: "43 21 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compliance:
    uses: SchwarzDigits/oss-compliance/.github/workflows/full-check.yml@4ff64dca8c04a92c95d9bdcfc1c3ea136d584890
