name: Compliance

on:
  pull_request:
  push: { branches: [main] }
  schedule:
    - cron: "43 21 * * 0"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compliance:
    uses: SchwarzDigits/oss-compliance/.github/workflows/full-check.yml@57231dcdb15140ed082ff579ec3c04179cbc8ca7
