name: Deploy Turbo Remote Cache
on:
  push:
    branches:
      - "main"
    paths:
      - "apps/turbo-remote-cache/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to CloudFoundry
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: "🛃 Harden the runner (Audit all outbound calls)"
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit
      - name: "🛒 Checkout Repository"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: ⛅️ Deploy to Cloud Foundry
        uses: ./.github/templates/cf-push
        with:
          endpoint: ${{ vars.CF_ENDPOINT }}
          org: ${{ vars.CF_ORG }}
          username: ${{ vars.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          space: prod
          varArgs: "--var TURBO_TOKEN=${{ secrets.TURBO_REMOTE_CACHE__TURBO_TOKEN }} --var AWS_ACCESS_KEY_ID=${{ secrets.TURBO_REMOTE_CACHE__AWS_ACCESS_KEY_ID }} --var AWS_SECRET_ACCESS_KEY=${{ secrets.TURBO_REMOTE_CACHE__AWS_SECRET_ACCESS_KEY }}"
          working-directory: apps/turbo-remote-cache/.cloud-foundry

      - name: Apply lifecycle rule
        working-directory: apps/turbo-remote-cache/
        run: |
          echo "s3cmd==2.4.0 --hash=sha256:13ad8a44d44cc0535ba8c878c91fd68cd830dc48f6388722fa44a7aaf3f18017" > requirements.txt
          sudo pip install -r requirements.txt --require-hashes

          s3cmd \
            --host-bucket="%(bucket)s.object.storage.eu01.onstackit.cloud" \
            --host="object.storage.eu01.onstackit.cloud" \
            --region="eu01" \
            --access_key="${{ secrets.TURBO_REMOTE_CACHE__AWS_ACCESS_KEY_ID }}" \
            --secret_key="${{ secrets.TURBO_REMOTE_CACHE__AWS_SECRET_ACCESS_KEY }}" \
            setlifecycle ./lifecycle_policy.xml s3://turbo-remote-cache
