name: Export Figma variables
on:
  workflow_dispatch:

jobs:
  export:
    name: Export Figma variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: pnpm

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🛠️ Build Figma utils
        run: pnpm run build
        working-directory: packages/figma-utils

      - name: Export variables
        run: npx @nui/figma-utils export --file-key "${{ secrets.FIGMA_FILE_KEY }}" --token "${{ secrets.FIGMA_TOKEN }}" --prefix nui
        working-directory: packages/nui/src/styles

      - name: Upload variables artifact
        uses: actions/upload-artifact@v3
        with:
          name: variables
          path: packages/nui/src/styles/variables.css

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "feat: update Figma variables"
          title: "feat: update Figma variables"
          body: This is an auto-generated pull request. All Figma variables have been updated / exported.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
