name: Prepare Version
on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  changeset-action:
    name: Run Changeset Action
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: "🛃 Harden the runner (Audit all outbound calls)"
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: "🛒 Checkout Repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ssh-key: ${{ secrets.GH_PUSH_PROTECTED_KEY }}
          fetch-depth: 0

      - uses: ./.github/templates/node-setup

      - name: Create Pull Request
        uses: changesets/action@198f833dd7d863100ea6e28967bc9a9fdefadb0a # v2.1.0
        with:
          publish: "exit 1" # Fail on publish - Should always only create a PR
          createGithubReleases: false
          title: "chore: update onyx versions and changelogs for release"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
