name: Reusable workflow for importing Figma variables

on:
  workflow_call:
    inputs:
      modes:
        type: string
        required: true
      selector:
        type: string
        required: true
      output-directory:
        type: string
        required: true
      format:
        type: string
        default: CSS
      file-prefix:
        type: string
        default: ""

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - run: |
          pnpm run @sit-onyx/figma-utils import-variables -k "${{ vars.FIGMA_FILE_KEY }}" -t "${{ secrets.FIGMA_TOKEN }}" -d "${{ inputs.output-directory }}" -m ${{ inputs.modes }} -f ${{ inputs.format }} -s "${{ inputs.selector }}" -n "${{ inputs.file-prefix }}"
        working-directory: packages/figma-utils
